config/routes.rb
TransportAdder::Application.routes.draw do
  resources :transports do
    resources :lines
    resources :docking_stations
  end
    
  resources :visualizations, :only => [:index]  
  
  resources :docking_stations, :except => [:edit, :update, :show]
  resources :stations
  
  resources :ways, :only => [:destroy]
  
  resources :segments
  
  resources :lines do
    resources :stations
    resources :connections
    resources :segments
    resources :ways, :only => [:create]
  end
  
  resources :vehicles
  
  resources :connections
  
  post "/traversals/:line_id/generate_automatic" => "traversals#generate_automatic", :as => :traversal_generate_automatic
  delete "/traversals/:line_id/destroy_automatic" => "traversals#destroy_automatic", :as => :traversal_destroy_automatic
  
  resources :traversals
  

  root :to => 'transports#index'

end

app/models/line.rb
class Line < ActiveRecord::Base
  has_many :ways
  has_many :stations
  has_many :segments
  has_many :vehicles
  
  belongs_to :transport
  
  validates_presence_of :name, :right_terminal, :left_terminal, :transport
  
  def self.all_except(line)
    self.where('id != ?', line.id)
  end
  
  def connections
    Connection.find_all_from_line(self)
  end
  
  def line_transport
    "#{self.transport.name} - #{self.name}"
  end
  
  def name_by_directions
    "#{left_terminal} - #{right_terminal}"
  end
  
  def can_generate_basic_traversals?
    get_terminals.length==2
  end
  
  def basic_traversals
    one_st, another_st = get_terminals
    return [] if one_st.nil? && another_st.nil?
    
    Traversal.where('(one_station_id = :s1 AND another_station_id = :s2) OR (one_station_id = :s2 AND another_station_id = :s1)', 
      {:s1 => one_st, :s2 => another_st})
  end
  
  def generate_basic_traversals
    Traversal.build_new_between!(right_terminal, left_terminal, :by => id)
    Traversal.build_new_between!(left_terminal, right_terminal, :by => id)
  end
  
  private
  
  def get_terminals
    Station.where('(name = :name_right OR name = :name_left) AND line_id = :line_id', {:name_right => right_terminal, :name_left => left_terminal, :line_id => id})
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  def index
    @transports = Transport.find(:all, :include => [:lines])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @line = Line.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    @line = Line.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @line = Line.find(params[:id])
  end

  def create
    @line = Line.new(params[:line])

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, :notice => I18n.t('lines.create.messages.saved') }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @line = Line.find(params[:id])

    respond_to do |format|
      if @line.update_attributes(params[:line])
        format.html { redirect_to @line, :notice => I18n.t('lines.update.messages.saved') }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy

    respond_to do |format|
      format.html { redirect_to lines_url, :notice => I18n.t('lines.destroy.messages.done') }
    end
  end
end

app/helpers/lines_helper.rb
module LinesHelper
  
  def station_for_line(line, connection)
    connection.another_line == line ? connection.one_station_id : connection.another_station_id
  end
end

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
		<div class="simple-form">
    	<%= f.label :name, t('activerecord.attributes.line.name') %>
	    <%= f.text_field :name %>

			<%= f.label :name, t('activerecord.attributes.line.simple_identifier') %>
	    <%= f.text_field :simple_identifier %>

	    <%= f.label :right_terminal, t('activerecord.attributes.line.right_terminal') %>
	    <%= f.text_field :right_terminal %>

			<%= f.label :left_terminal, t('activerecord.attributes.line.left_terminal') %>
	    <%= f.text_field :left_terminal %>

	    <%= f.label :color, t('activerecord.attributes.line.color') %>
	    <%= f.text_field :color %>

	    <%= f.label :transport, t('activerecord.attributes.line.transport') %>
	    <%= f.select :transport_id, options_from_collection_for_select(Transport.all, 'id', 'name', @line.transport_id), {:include_blank => true} %>
		</div>
    <%= f.submit t('actions.save') %>
<% end %>

app/views/lines/_line.html.erb
<div id="line-<%= line.id %>" class="listed-block shadow-right-bottom rounded-8">
	<span class="name left"><%= link_to line.name, line %></span>
	<span class="name_by_directions middle"><%= line.name_by_directions %></span>
	
	<span class="right inlined">
		<%= button_to t('actions.delete'), line_path(line), 
				:method => :delete, 
				:confirm => t('messages.destroy_confirmation') %>
	  <%= link_to t('actions.edit'), edit_line_path(line) %>
	</span>
</div>

app/views/lines/edit.html.erb
<% if @line.errors.any? %>
	<%= content_for :alerts do %>
		<%= t('lines.update.messages.not_saved') %>
	<% end %>
<% end %>

<% content_for :header do %>
	<%= t('lines.edit.title') %>
<% end %>

<br/>

<div class="block">
	<%= render 'form' %>
</div>

<% content_for :footer do %>
	<%= link_to t('actions.back'), :back %>
<% end %>

app/views/lines/index.html.erb
<h1><%= t('lines.index.title') %></h1>

<p class="section-button"><%= link_to t('actions.lines.add'), new_line_path %></p>

<% @transports.each  do |transport| %>
	
	<div id="transport-<%= transport.id %>">
		<% unless transport.transport_mode_is?(:bike_sharing) %>
			<p class="section-name"><%= transport.name %></p>
			<div class="main-content block">
				<% if transport.lines.empty? %>
					<%= t('lines.index.no_records') %>
				<% else %>
					<% transport.lines.each do |line| %>
						<%= render line %>
					<% end %>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>

app/views/lines/new.html.erb
<% if @line.errors.any? %>
	<% content_for :alerts do %>
		<%= t('lines.create.messages.not_saved') %>
	<% end %>
<% end %>

<% content_for :header do %>
	<%= t('lines.new.title') %>
<% end %>

<br/>

<div class="block">
	<%= render 'form' %>
</div>

<% content_for :footer do %>
	<%= link_to t('actions.back'), lines_path, :class => "back-link" %>
<% end %>

app/views/lines/show.html.erb
<%= render :partial => 'shared/sub_header', :locals => {:line => @line } %>

<div class="traversal-basic rounded-5">
	<%= render :partial => 'traversals/automatic_generation' %>
</div>
<% content_for :raw do %>
	<div class="block">
		
		<ul class="service-numbers">
			<% [:ways, :stations, :segments, :connections].each do |item| %>
				<%= render :partial => 'shared/children_count', :locals => { :model_from => @line, :property => item }%>
			<% end %>
		</ul>
		
		<div class="ways subsection">
			<%= render 'ways/index' %>
		</div>
		<div class="divider"></div>
		<div class="stations subsection">
			<%= render :partial => 'stations/index', :locals => {:station_line => @line } %>
		</div>
		<div class="divider"></div>
		<div class="segments subsection">
			<%= render :partial => "segments/index", :locals => {:station_line => @line } %>
		</div>
		<div class="divider"></div>
		<div class="connections subsection">
			<%= render :partial => "connections/index", :locals => {:station_line => @line } %>
		</div>
	
	</div>
<% end %>

<% content_for :footer do %>
	<%= link_to t('actions.back'), lines_path %>
	<%= link_to t('actions.edit'), edit_line_path(@line), :class => "to-right modify" %>
<% end %>