config/routes.rb
TransportAdder::Application.routes.draw do
  resources :transports do
    resources :lines
    resources :docking_stations
  end
    
  resources :visualizations, :only => [:index]  
  
  resources :docking_stations, :except => [:edit, :update, :show]
  resources :stations
  
  resources :ways, :only => [:destroy]
  
  resources :segments
  
  resources :lines do
    resources :stations
    resources :connections
    resources :segments
    resources :ways, :only => [:create]
  end
  
  resources :vehicles
  
  resources :connections
  
  post "/traversals/:line_id/generate_automatic" => "traversals#generate_automatic", :as => :traversal_generate_automatic
  delete "/traversals/:line_id/destroy_automatic" => "traversals#destroy_automatic", :as => :traversal_destroy_automatic
  
  resources :traversals
  

  root :to => 'transports#index'

end

app/models/transport.rb
class Transport < ActiveRecord::Base
  has_many :lines
  has_many :docking_stations
  
  validates_presence_of :name, :mode
  
  def self.modes
    { 1 => :bike_sharing, 2 => :subway, 3 => :bus_rapid_transit, 4 => :bus, 5 => :light_tram, 6 => :commuter_rail}
  end
  
  def self.humanized_modes
    self.modes.keys.each.inject({}) { |collected, key| collected[key] = self.modes[key].to_s.humanize ; collected }
  end
  
  def self.mode_for(mode)
    self.modes.invert[mode]
  end
  
  def humanized_mode
    Transport.modes[self.mode].to_s.humanize
  end
  
  def transport_mode_is?(mode)
    return self.mode==Transport.mode_for(mode)
  end
end

app/controllers/transports_controller.rb
class TransportsController < ActionController::Base
  
  layout 'application'
  
  before_filter :find_transport, :only => [:show, :edit, :update]
  
  def new
    @transport = Transport.new
  end
  
  def create
    @transport = Transport.new(params[:transport])
    
    if @transport.save
      redirect_to @transport, :notice => I18n.t('transports.create.messages.saved')
    else
      render :action => :new
    end
    
  end
  
  def show
  end
  
  def index
    @transports = Transport.all
  end
  
  def edit
  end
  
  def destroy
    @transport = Transport.find(params[:id])
    @transport.destroy

    respond_to do |format|
      format.html { redirect_to transports_url, :notice => I18n.t('transports.destroy.messages.done') }
    end
  end
  
  def update
    if @transport.update_attributes(params[:transport])
      redirect_to @transport, :notice => I18n.t('transports.update.messages.saved')
    else
      render :action => :edit
    end
  end
  
  private
  def find_transport
    @transport = Transport.find(params[:id])
  end
end

app/helpers/transports_helper.rb
module TransportsHelper
  
  def count_humanized_with(translation, count)
    html="<span class=\"number\">"
    if count==1
      html << t("#{translation}.one", :number => count)
    else
      html << t("#{translation}.other", :number => count)
    end
    html << "</span>"
  end
end

app/views/transports/_bike_sharing.html.erb
<%= render :partial => 'docking_stations/transport_header', 
					 :locals => {:transport => @transport } %>
					
<ul class="service-numbers">
	<%= render :partial => 'shared/children_count', :locals => { :model_from => @transport, :property => :docking_stations }%>
</ul>


<% content_for :raw do %>
	<div class="block">
		<div class="docking-stations subsection">
			<%= render 'docking_stations/index' %>
		</div>
	</div>
<% end %>

app/views/transports/_common.html.erb
<h1><%= t('transports.show.title') %></h1>
<p><span class="name attr-display">
	<%= t('activerecord.attributes.transport.name') %>: </span>
	<%= @transport.name %>
</p>

<% unless @transport.twitter.blank? %>
	<p><span class="attr-display">
		<%= t('activerecord.attributes.transport.twitter') %>: </span>
		<span class="twitter">@<%= @transport.twitter %></span>
	</p>
<% end %>

<p><span class="mode attr-display">
	<%= t('activerecord.attributes.transport.mode') %>: </span>
	<%= @transport.humanized_mode %>
</p>

<p><span class="lines-stations attr-display">
	<%= t('activerecord.attributes.transport.lines')%>:
	</span>
	<%= count_humanized_with('messages.lines.number', @transport.lines.count).html_safe %>
</p>

app/views/transports/_form.html.erb
<%= f.label :name, t('activerecord.attributes.transport.name') %>
<%= f.text_field :name, :id => "transports_name" %><br/>

<%= f.label :name, t('activerecord.attributes.transport.popular_name') %>
<%= f.text_field :popular_name %>

<%= f.label :mode, t('activerecord.attributes.transport.mode') %>
<%= f.select :mode, options_for_select(Transport.humanized_modes.invert, @transport.mode), {:include_blank => true}, :id => "transports_mode" %><br/>

<%= f.label :web_page, t('activerecord.attributes.transport.web_page') %>
<%= f.text_field :web_page, :id => "transports_web_page" %><br/>
<%= f.label :twitter, t('activerecord.attributes.transport.twitter') %>
<%= f.text_field :twitter, :id => "transports_twitter" %><br/>

<br/><br/>
<%= f.check_box :merge_stations_with_same_name, {}, @transport.merge_stations_with_same_name %>
<b><%= t('activerecord.attributes.transport.merge_stations_with_same_name') %></b>

app/views/transports/_transport.html.erb
<div id="transport-<%= transport.id %>" class="listed-block shadow-right-bottom rounded-8">
	<span class="name left"><%= link_to transport.name, transport %></span>
	
	<span class="right">
	<% unless transport.transport_mode_is?(:bike_sharing) %>
			<%= link_to t('actions.lines.see'), transport_lines_path(transport) %>
	<% end %>
	</span>
</div>

app/views/transports/edit.html.erb
<% if @transport.errors.any? %>
	<%= t('transports.update.messages.not_saved') %>
<% end %>

<% content_for :header do %>
	<%= t('transports.edit.title') %>
<% end %>

<br/>

<div class="block">
	<%= form_for @transport, :method => :put do |f| %>
		<div class="simple-form">
			<%= render :partial => 'form', :locals => {:f => f} %>
		</div>
		<%= f.submit t('actions.save'), :class => "submit-button" %>
	<% end %>
</div>


<% content_for :footer do %>
	<%= link_to t('actions.back'), transports_path %>
<% end %>

app/views/transports/index.html.erb
<h1><%= t('transports.index.title') %></h1>

<p class="section-button"><%= link_to t('actions.transports.add'), new_transport_path %></p>

<div class="main-content">
	<% if @transports.empty? %>
		<%= t('transports.index.no_records') %>
	<% else %>
		<%= render @transports %>
	<% end %>
</div>

app/views/transports/new.html.erb
<% if @transport.errors.any? %>
	<% content_for :alerts do %>
		<%= t('transports.create.messages.not_saved') %>
	<% end %>
<% end %>

<% content_for :header do %>
	<%= t('transports.new.title') %>
<% end %>

<br/>

<div class="block">
	<%= form_for @transport do |f| %>
		<div class="simple-form">
			<%= render :partial => 'form', :locals => {:f => f} %>
		</div>
		<%= f.submit t('actions.save'), :class => "submit-button" %>
	<% end %>
</div>

<% content_for :footer do %>
	<%= link_to t('actions.back'), transports_path %>
<% end %>

app/views/transports/show.html.erb
<div class="show block">
	<% if @transport.transport_mode_is?(:bike_sharing) %>
		<%= render "bike_sharing" %>
	<% else %>
		<%= render 'common' %>
	<% end %>
</div>

<% content_for :footer do %>
	<%= link_to t('actions.back'), transports_path %>
	
	<div class="to-right inlined">
		<%= link_to t('actions.edit'), edit_transport_path(@transport), :class => "modify" %>
		<%= button_to t('actions.delete'), transport_path(@transport), 
			:method => :delete, :confirm => I18n.t('messages.destroy_confirmation') %>
	</div>
<% end %>