config/routes.rb
TransportAdder::Application.routes.draw do
  resources :transports do
    resources :lines
    resources :docking_stations
  end
    
  resources :visualizations, :only => [:index]  
  
  resources :docking_stations, :except => [:edit, :update, :show]
  resources :stations
  
  resources :ways, :only => [:destroy]
  
  resources :segments
  
  resources :lines do
    resources :stations
    resources :connections
    resources :segments
    resources :ways, :only => [:create]
  end
  
  resources :vehicles
  
  resources :connections
  
  post "/traversals/:line_id/generate_automatic" => "traversals#generate_automatic", :as => :traversal_generate_automatic
  delete "/traversals/:line_id/destroy_automatic" => "traversals#destroy_automatic", :as => :traversal_destroy_automatic
  
  resources :traversals
  

  root :to => 'transports#index'

end

app/views/shared/_children_count.html.erb
<li class="rounded-5">
	<% if (count=model_from.send(property).count)==1 %>
		<%= t("#{property.to_s}.index.count.one") %>
	<% else %>
		<%= t("#{property.to_s}.index.count.other", :number => count) %>
	<% end %>
</li>

app/views/shared/_menu.html.erb
<div class="sections">
	<%= link_to t('visualizations.index.title'), visualizations_path, :class => "rounded-5" %>
	<%= link_to Transport.model_name.human.pluralize, transports_path , :class => "rounded-5" %>
	<%= link_to Line.model_name.human.pluralize, lines_path , :class => "rounded-5" %>
	<%= link_to Traversal.model_name.human.pluralize, traversals_path, :class => "rounded-5" %>
	<%= link_to Vehicle.model_name.human.pluralize, vehicles_path, :class => "rounded-5" %>
</div>

app/views/shared/_sub_header.html.erb
<div class="hidden color-h"><%= line.color %></div>
<div class="sub-header colorable">
	<h1><span class="transport"><%= line.transport.name %></span> - <span class="agrouper"><%= line.name %></span> </h1>
	<span class="name-by-directions"><%= line.name_by_directions %></span>
</div>