config/routes.rb
TransportAdder::Application.routes.draw do
  resources :transports do
    resources :lines
    resources :docking_stations
  end
    
  resources :visualizations, :only => [:index]  
  
  resources :docking_stations, :except => [:edit, :update, :show]
  resources :stations
  
  resources :ways, :only => [:destroy]
  
  resources :segments
  
  resources :lines do
    resources :stations
    resources :connections
    resources :segments
    resources :ways, :only => [:create]
  end
  
  resources :vehicles
  
  resources :connections
  
  post "/traversals/:line_id/generate_automatic" => "traversals#generate_automatic", :as => :traversal_generate_automatic
  delete "/traversals/:line_id/destroy_automatic" => "traversals#destroy_automatic", :as => :traversal_destroy_automatic
  
  resources :traversals
  

  root :to => 'transports#index'

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  belongs_to :origin_station, :foreign_key => :origin_station_id, :class_name => "Station"
  belongs_to :destination_station, :foreign_key => :destination_station_id, :class_name => "Station"
  belongs_to :line
  
  validate :stations_are_different
  
  validate :has_unique_stations, :on => :create
  validate :has_unique_stations_preserving_id, :on => :update
  
  validates_presence_of :origin_station, :destination_station
  
  private
  def stations_are_different
    if origin_station == destination_station
      self.errors.add(:origin_station)
      self.errors.add(:destination_station)
    end
  end
  
  def has_unique_stations_preserving_id
    conditions = '((origin_station_id = :o_id AND destination_station_id = :d_id) OR (origin_station_id = :d_id AND destination_station_id = :o_id)) AND id <> :id'
    stations_uniqueness_for(conditions)
  end
  
  def has_unique_stations
    conditions = '(origin_station_id = :o_id AND destination_station_id = :d_id) OR (origin_station_id = :d_id AND destination_station_id = :o_id)'
    stations_uniqueness_for(conditions)
  end
  
  def stations_uniqueness_for(conditions)
    if Segment.where(conditions, {:o_id => origin_station_id, :d_id => destination_station_id, :id => id}).count > 0
      self.errors.add(:origin_station)
      self.errors.add(:destination_station)
    end
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ActionController::Base
  layout 'application'
    
  def new
    @line = Line.find(params[:line_id])
    @segment = Segment.new
  end
  
  def create
    @segment = Segment.new(params[:segment])
    @line = @segment.line
    
    if @segment.save
      redirect_to(@segment.line, :notice => I18n.t('segments.create.messages.saved'))
    else
      render :action => :new
    end
  end
  
  def destroy
    @segment = Segment.find(params[:id])
    @segment.destroy
    redirect_to(@segment.line, :notice => I18n.t('segments.destroy.messages.done'))
  end
  
  def edit
    @segment = Segment.includes(:line).find(params[:id])
    @line = @segment.line
  end
  
  def update
    @segment = Segment.find(params[:id])
    @line = @segment.line
    
    if @segment.update_attributes(params[:segment])
      redirect_to(@segment.line, :notice => I18n.t('segments.update.messages.saved'))
    else
      render :action => :edit
    end
  end
  
end

app/views/segments/_form.html.erb
<div class="simple-form">
	<div class="inlined-spaced">
		<div>
			<%= f.label :origin_station, t('activerecord.attributes.segment.origin_station') %>
			<%= f.select :origin_station_id, options_from_collection_for_select(@line.stations, "id", "name", @segment.origin_station_id) %>
		</div>
		<div>
			<%= f.label :destination_station, t('activerecord.attributes.segment.destination_station') %>
			<%= f.select :destination_station_id, options_from_collection_for_select(@line.stations, "id", "name", @segment.destination_station_id) %>
		</div>
	</div>
	
	<%= f.hidden_field :line_id, :value => @line.id %>
	<br/>
	<br/>
	<%= f.check_box :double_direction, :checked => @segment.double_direction || true %> 
	<b><%= t('segments.form.build_two_way_segment') %></b>
	<%= f.label t('stations.new.sub_form.fields.distance') %>
	<%= f.text_field :distance %> <%= t('stations.new.sub_form.kms') %>
</div>

<%= f.submit t('actions.save') %>

app/views/segments/_index.html.erb
<div class="new-segment inlined">
	<h2><%= t('segments.index.title') %></h2>
	<h3><span>+</span><%= link_to t('segments.new.title'), new_line_segment_path(station_line) %></h3>
</div>
<br/>

<% if station_line.segments.empty? %>
	<%= t('segments.index.no_records') %>
<% else %>
	<%= render station_line.segments %>
<% end %>

app/views/segments/_segment.html.erb
<div class="segment inlined rounded-5" id="segment-<%= segment.id %>">
	<span class="origin"><%= segment.origin_station.name %></span>
	<span class="direction"><%= segment.double_direction ? "<->" : ">" %></span>
	<span class="destination"><%= segment.destination_station.name %></span>
	
	<span class="actions">
		<%= link_to t('actions.edit'), edit_segment_path(segment) %>
		<%= button_to t('actions.delete'), segment, :method => :delete, :confirm => t('messages.destroy_confirmation') %>
	</span>
</div>

app/views/segments/edit.html.erb
<% if @segment.errors.any? %>
	<% content_for :alerts do %>
		<%= t('segments.update.messages.not_saved') %>
	<% end %>
<% end %>

<% content_for :header do %>
	<%= t('segments.edit.title') %>
<% end %>

<%= render :partial => 'shared/sub_header', :locals => {:line => @line } %>

<div class="block">
	<%= form_for @segment, :method => :put do |f| %>
		<%= render :partial => 'form', :locals => {:f => f} %>
	<% end %>
</div>

<% content_for :footer do %>
	<%= link_to t('actions.back'), line_path(@line) %>
<% end %>

app/views/segments/new.html.erb
<% if @segment.errors.any? %>
	<% content_for :alerts do %>
		<%= t('segments.create.messages.not_saved') %>
	<% end %>
<% end %>

<% content_for :header do %>
	<%= t('segments.new.title') %>
<% end %>

<%= render :partial => 'shared/sub_header', :locals => {:line => @line } %>

<div class="block">
	<%= form_for @segment do |f| %>
		<%= render :partial => 'form', :locals => {:f => f} %>
	<% end %>
</div>

<% content_for :footer do %>
	<%= link_to t('actions.back'), line_path(@line) %>
<% end %>